### PR TITLE
Form validation

### PR DESCRIPTION
**Pull request by lpsBetty**
@leocaseiro can you please review this PR...

I added an angular convention - when an user interacts with an input field it will set the model to `$touched` .. with our chosen this was not the case!

The user was able to open the select and close it and the model itself stayed `$untouched`.

This requires Angular 1.3+, so maybe take a look if this makes sense for you - I also added an example for demo purposes.

### CODE REVIEW

**Comment by leocaseiro** [comment]
@lpsBetty thank you for your nice work.

I agree we shouldn't need `vendor`, however, I believe we should use 100% cdn on examples. Some users download from github, without npm and bower. In that case, they should be able to download and test without any node package manager.

Also if we have as a cdn, we can use htmlpreview as another examples link:
http://htmlpreview.github.io/?https://github.com/leocaseiro/angular-chosen/blob/master/example/index.html

Yeah, npm for tests is perfect, because we need to run npm install to test anyway. We wouldn't need bower as I talked last time! Perfect!

How about we use https://cdnjs.com/libraries/chosen for chosen and google for jquery and angular examples?
I don't mind what cdn to use. Up to you.

**Comment by leocaseiro** [comment]
In regards the validation, sorry I haven't test your PR yet, but would that work for ng-required without the CSS hack? If yes, that is AWESOME!

**Comment by lpsBetty** [comment]
ok didn't know why CDNs were used in the example - but now it makes total sense ;) 
I am gonna change that of course!

There is an CSS hack? :D

**Comment by leocaseiro** [comment]
Yeah, actually it does: https://github.com/leocaseiro/angular-chosen/issues/169#issuecomment-194815291

**Pull request merged**
