### PR TITLE
Chosen update - add karma tests

### LINKED ISSUE #80: add support for latest version of chosen
It would be great if you could officially support chosen 1.2.0. There have been a lot of bug fixes since 1.0.0.

### PR DESCRIPTION
**Pull request by lpsBetty**
hey @leocaseiro!
I updated chosen.query - tried the example/index.html and it works as expected!
I also added some basic tests in this branch - maybe you can tell me what would be important to test additionally!

I think adding tests here is not a bad idea ;)

Fix #80 #166

### CODE REVIEW

**Comment by kfarst** [comment]
@IpsBetty for the chosen version update you might wanna check out https://github.com/leocaseiro/angular-chosen/pull/168

**Comment by kfarst** [comment]
Also no problem, some of your changes are similar to the changes I've already made 😉

**Comment by lpsBetty** [comment]
@kfarst do you want to merge it in this branch?

**Comment by leocaseiro** [comment]
Very nice @lpsBetty!
Loved it. Now we can add Travis to our repo!

That would be interesting to add './test' dir to be ignored for bower and npm. Also include the `test` on `gulp build` task, so if any test fails, gulp should warn about it before compile.

Do you wanna try implement that?

**Comment by lpsBetty** [comment]
@kfarst but `chosen-npm` is also not the 'real' chosen, it is an old version - but they will release the original on npm soon: https://github.com/harvesthq/chosen/issues/1433

**Comment by lpsBetty** [comment]
@leocaseiro  what do you mean by

> That would be interesting to add './test' dir to be ignored for bower and npm.

**Comment by kfarst** [comment]
@lpsBetty @leocaseiro go ahead and merge this PR in when you're done with it, I'll rebase and fix any merge conflicts when I'm done, but I'll definitely use a lot of what you did @lpsBetty

**Comment by leocaseiro** [comment]
I meant to ignore from bower and npm, so who download from package manager don't need to have tests, though: a266f1081d89726

**Comment by leocaseiro** [comment]
Thanks for that AWESOME work, btw!

**Comment by leocaseiro** [comment]
@lpsBetty I've got an error trying to install chosen-npm#1.5.1, had to select 1.4.2. I'll keep 1.4.2 in our package.json until they release the 1.5.0 into npm.

**Comment by lpsBetty** [comment]
ah ok :) yeah that's ok!

**Pull request merged**
