### PR TITLE
Fix #189: Select element "flickers" on first page load

### LINKED ISSUE #189: Select element "flickers" on first page load
The use of $timeout (angular-chosen.js, line 72, see below) postpones the initialization of the chosen plugin to a later digest cycle. Because of that, the plain HTML select element will be painted first, leading to an ugly "flickering effect".
```
             $timeout(function() {
                chosen = element.chosen(options).data('chosen');
              });
```
Another approach to make sure the DOM is ready (without flickering) would be the default jQuery way:
```
              $(document).ready(function () {
                chosen = element.chosen(options).data('chosen');
              });
```

### PR DESCRIPTION
**Pull request by boeserwolf**

### CODE REVIEW

**Comment by leocaseiro** [comment]
Hi @boeserwolf, thanks for updating the tests. I really appreciate that.

However, it seems no tests are really running. I've tried to fail them, switching from true to false and so on, but they still passing through.

I believe karma doesn't wait for the dom to run the tests. I did some research about that, and I'll need to move the tests for a service.

- http://stackoverflow.com/questions/27830126/jasmine-test-angular-elementdocument-ready
- http://stackoverflow.com/questions/30357261/unit-test-an-angularjs-document-ready-function

**Comment by boeserwolf** [comment]
Hi @leocaseiro, thanks for your reply. Sorry, my bad, I should really have tested that.

After doing some further research, it looks like there's just no need for $document.ready() or $timeout(), because Angular won't initialize until the DOM was loaded:
```
jqLite(window.document).ready(function() {
    angularInit(window.document, bootstrap);
  });

})(window);
```
So, as far as I understand, we should be good with just calling element.chosen(). I've updated the pull request correspondingly. Are you solving another specific issue by wrapping the statement with $timeout()?

Thanks!

**Comment by leocaseiro** [comment]
Hi @boeserwolf,

Thanks again.

Unfortunately, I had to add $timeout to solve the issue #176

I'll need to work on this on the weekend. I'd like to have a solution for both issues.

**Comment by liorch88** [comment]
Seems #213 solves it

**Comment by leocaseiro** [comment]
Closes in regards to #213
Thanks for all help guys!

**Pull request closed without merging**
