### PR TITLE
Cannot read property 'default_text' of undefined

### PR DESCRIPTION
**Pull request by kfarst**
TypeError: Cannot read property 'default_text' of undefined
    at angular.module.directive.link.initOrUpdate (http://localhost:9000/vendor/angular-chosen-localytics/chosen.js:59:40)
    at angular.module.directive.link.ngModel.$render (http://localhost:9000/vendor/angular-chosen-localytics/chosen.js:74:20)
    at updateOptions (http://localhost:9000/vendor/angular/angular.js:26433:21)
    at Object.$watchCollectionAction [as fn] (http://localhost:9000/vendor/angular/angular.js:15550:13)
    at Scope.$get.Scope.$digest (http://localhost:9000/vendor/angular/angular.js:15683:29)
    at Scope.$get.Scope.$apply (http://localhost:9000/vendor/angular/angular.js:15951:24)
    at done (http://localhost:9000/vendor/angular/angular.js:10364:47)
    at completeRequest (http://localhost:9000/vendor/angular/angular.js:10536:7)
    at XMLHttpRequest.requestLoaded (http://localhost:9000/vendor/angular/angular.js:10477:9) undefined

### CODE REVIEW

**Comment by kfarst** [comment]
@leocaseiro I apparently deleted my forked version forgetting I had opened the PR for this fix, here's the new one without merge conflicts

**Comment by leocaseiro** [comment]
Sorry, @kfarst. Would you mind compile the chosen.js before I accept the PR?

Many thanks!

**Comment by kfarst** [comment]
Sorry about that @leocaseiro, compiled and amended in 29d0999339063f4dd9e96db4d65502d4fb25648a

**Comment by leocaseiro** [comment]
Thanks @kfarst I appreciate it. Will launch next version.

**Pull request merged**
