### PR TITLE
Allow Angular to use jqLite

### PR DESCRIPTION
**Pull request by Robinson7D**
This allows JQuery to be loaded after Angular, improving general app performance.

Plunker showing the old way (broken if you include AngularJS before Chosen):
http://plnkr.co/edit/5xfn1H7boZ6JEF9WDpaT?p=preview

Plunker showing the new, working code:
http://plnkr.co/edit/9jiWkj0tKcPWAvwylfmK?p=preview

### CODE REVIEW

**Comment by raphaelduartepinheiro** [comment]
Good feature, I'd use this module, but the author(s) of this project seems dead. lol

**Comment by akotlar** [comment]
Thanks!

**Comment by leocaseiro** [comment]
I'm very happy to merge this PR. 
Could you please update your repo with the last version of chosen and update your PR?

Thanks

**Comment by leocaseiro** [comment]
I couldn't get from your PR, so I made on my own!

**Pull request closed without merging**
