### PR TITLE
Observe attributes and update options on change. Update default text on every attribute update.

### PR DESCRIPTION
**Pull request by vstene**

### CODE REVIEW

**Comment by leocaseiro** [comment]
Hi @vstene. Thanks for your PR.

I've just take this project and I would like to know about your scenario. Could you please explain me why would be necessary? Would you mind creating a plunkr for me?

You can fork from this example though: http://plnkr.co/edit/1U8KCH?p=preview

Thanks

**Comment by vstene** [comment]
Hello @leocaseiro,

I have a multi language app and I need to refresh the text attributes on language change. The problem seem to be that the attributes are not watched.

For example, when changing the scope variable the text is not updated:
http://plnkr.co/edit/vQt1mI2U9ecBMf4SkGE0?p=preview

From the current version of my fork the binding is applied via `attr.$observe`:
http://plnkr.co/edit/yOBllVXEEVhklzw7Xb5V?p=preview

Hope this helps.

**Comment by leocaseiro** [comment]
Hi @vstene thank you for your reply.

I liked it. I'm going to resolve some conflicts and them I'll accept your PR.

I just would remove the reference from [chosen.set_default_text()](https://github.com/vstene/angular-chosen/blob/49031cff4cf04bdb10d10702dcb7b61ae41007cc/src/chosen.coffee#L52) which gives me a warning:

> TypeError: Cannot read property 'set_default_text' of null

**Comment by leocaseiro** [comment]
So we don't need the methods disableWithMessage() and removeEmptyMessage() as the updateMessage() would work for both, right?

**Comment by leocaseiro** [comment]
I created the branch [128-vind-placeholder-text-single]() which should fix your issue. I resolved all conflicts with the last PR's. Could you please double check if works for you?
So I'll merge into master and release **1.2.1** with this enhancement

Thanks

**Comment by vstene** [comment]
I don't remember the reason for the `set_default_text()`, but it seems to work now without.

**Comment by leocaseiro** [comment]
Hi @vstene I believe those changes broke few others chosen attributes, I'll have to restore it and rethink in another solution to your issue.

**Pull request closed without merging**
