### PR TITLE
Add chosen options units tests

### PR DESCRIPTION
**Pull request by kfarst**
- add jasmine-matchers package
- create chosen select helper
- move test support files into support folder
- update naming convention for spec files for cleaner filename matching
- add case converter filter for test support

### CODE REVIEW

**Comment by kfarst** [comment]
@leocaseiro added more unit tests and updated the testing configuration a little bit, let me know if you'd like anything changed up!

**Comment by leocaseiro** [comment]
Hi @kfarst, first of all, many many thanks for this amazing contribution.
I loved the `chosenSelectHelper.js`

I was wondering if you could help my issue. I had to add a $timeout to fix the issue #176, however, it has broken 17 tests which is not nice...

Is there a way to go way with that in the tests or my fix is not the best one? 
thanks

I have a branch for testing [176-ng-if-breaks-inherit-select-classes](https://github.com/leocaseiro/angular-chosen/tree/176-ng-if-breaks-inherit-select-classes)

**Comment by kfarst** [comment]
@leocaseiro What error are you getting? When I checkout that branch and run tests I get the error

`ReferenceError: Can't find variable: initOrUpdate` 

for almost all the broken tests, because the function was removed [here](https://github.com/leocaseiro/angular-chosen/commit/cb9d2b0744173b0d4d1f0e4e6bf3bdc073d998a4#diff-1cfdeb59a8976dcd8695887aa4618dacL75). If that function was meant to be removed, you should probably remove any additional references to it first, then we can go from there :+1:

**Comment by leocaseiro** [comment]
Hi @kfarst, thanks for your quick reply.

I actually made a biggest mistake while push the file. 
I've updated now 4c262334b0e1117f28d. It shouldn't return any JS error, only some tests that are running before `$timeout`, so we get some values as empty or undefined.

screen shot 2016-03-23 at 5 39 06 am

**Comment by leocaseiro** [comment]
@kfarst I've wrapped all `it` in `$timeout` and it actually works. 57c3ab67ea55

I'm happy to refactor in a better way if you have some ideas.

**Comment by kfarst** [comment]
@leocaseiro see https://github.com/leocaseiro/angular-chosen/pull/184

**Pull request merged**
