### PR TITLE
Init chosen when no ng directives attached

### PR DESCRIPTION
**Pull request by milasevicius**

### CODE REVIEW

**Comment by VanTanev** [comment]
Hello @milasevicius. Thanks for your contribution.

Can you please explain the reasoning behind this PR? I suspect that the goal is to allow chosen to be used without `ng-model`, which is a use case I could see some merit behind.

I would have to ask that you remove the extra `natives` dependency though.

**Comment by milasevicius** [comment]
I am working on a project which is written in AngularJS, but have some legacy forms w/o ng-model, thats why I added last initialisation statement.

I removed `natives` dependency

**Comment by leocaseiro** [comment]
Hi @milasevicius, thank you for your PR.

could you please show a demo with your use case? Perhaps a demo app at plunked or codepen?

Thanks

**Comment by milasevicius** [comment]
Hi,

Sorry it took a while to respond. As I mentioned before, this MR fixes chosen initialisation, when ngModel and / or ngOptions are not presented on `<select></select>`

**Pull request closed without merging**
