### PR TITLE
Cannot read property 'default_text' of undefined

### PR DESCRIPTION
**Pull request by kfarst**
TypeError: Cannot read property 'default_text' of undefined
    at angular.module.directive.link.initOrUpdate (http://localhost:9000/vendor/angular-chosen-localytics/chosen.js:59:40)
    at angular.module.directive.link.ngModel.$render (http://localhost:9000/vendor/angular-chosen-localytics/chosen.js:74:20)
    at updateOptions (http://localhost:9000/vendor/angular/angular.js:26433:21)
    at Object.$watchCollectionAction [as fn] (http://localhost:9000/vendor/angular/angular.js:15550:13)
    at Scope.$get.Scope.$digest (http://localhost:9000/vendor/angular/angular.js:15683:29)
    at Scope.$get.Scope.$apply (http://localhost:9000/vendor/angular/angular.js:15951:24)
    at done (http://localhost:9000/vendor/angular/angular.js:10364:47)
    at completeRequest (http://localhost:9000/vendor/angular/angular.js:10536:7)
    at XMLHttpRequest.requestLoaded (http://localhost:9000/vendor/angular/angular.js:10477:9) undefined

### CODE REVIEW

**Comment by kfarst** [comment]
@pkarl Just a heads up, this isn't just a console error, it actually breaks mobile Safari

**Comment by trueinviso** [comment]
Is this going to be fixed soon?  The code change here seems to resolve the error in the console but the data-placeholder is still blank on mobile.

**Comment by leocaseiro** [comment]
Hi @kfarst thank you for your PR.

Could you please update your branch with the last version of angular-chosen and resolve the conflicts?
This is very promising and I'm happy to accept it.

Thanks

**Comment by kfarst** [comment]
@leocaseiro updated PR here: https://github.com/leocaseiro/angular-chosen/pull/164

**Pull request closed without merging**
